### ISSUE TITLE
Link zu "Rückblick auf die Breminale"-Artikel ist kaputt

### ISSUE THREAD

**Issue by oliver** [FreifunkBremen/bremen.freifunk.net#10]
Der Link zum Blogpost "Rückblick auf die Breminale" (http://bremen.freifunk.net/blog/2015/07/29/breminale-r%C3%BCckblick.html) führt bei mir im Moment nur auf eine leere Seite. Getestet mit Firefox 41.

**Comment by jplitza** [comment]
War irgendein Problem beim Bauen der Seite mit Jekyll. Habe einmal den
Incremental Build Cache (`.jekyll-metadata`) gelöscht und die Seite neu
gebaut, nu lüppts.

**Comment by oliver** [comment]
Prima, danke!
