### ISSUE TITLE
Website voll Darkmode kompatibel machen.

### ISSUE THREAD

**Issue by Timi7007** [FreifunkBremen/bremen.freifunk.net#101]
Siehe z.B. das HSHB- oder TP-Link-Logo.

```prefers-color-scheme```?

Gesche hat folgende Screenshots gemacht:
![Screenshot_20190816-221104_Samsung Internet](https://user-images.githubusercontent.com/5683832/63195618-6765af00-c073-11e9-8f32-afa59449b5a8.jpg)
![Screenshot_20190816-221150_Samsung Internet](https://user-images.githubusercontent.com/5683832/63195619-6765af00-c073-11e9-8283-0e215e6363af.jpg)

**Comment by mortzu** [comment]
Kann das dann nicht zu?

**Comment by lokn** [comment]
fixed in #132
