### ISSUE TITLE
Google Events Issues

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/bremen.freifunk.net#111]
Seit dem Merge von #103 meckert Google hin und wieder per Mail an den Events rum:

>  Search Console
> 
> Events issues detected on bremen.freifunk.net
> 
> To the owner of bremen.freifunk.net:
> 
> Search Console has identified that your site is affected by 3 Events issues:
> 
> Top Errors
> 
> Errors can prevent your page or feature from appearing in Search results. The following errors were found on your site:
> 
> Missing field "location.address"
> 
> Invalid value type for field "location"
> 
> Top Warnings
> 
> Warnings are suggestions for improvement. Some warnings can affect your appearance on Search; some might be reclassified as errors in the future. The following warnings were found on your site:
> 
> Missing field "location.name"
> 
> We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.

**Comment by jortgies** [comment]
das liegt daran, dass die location auf {} gesetzt wird wenn sie im kalender ungleich "Hackerspace Bremen e.V." ist

#112 sollte das fixen indem zumindest der location.name gesetzt wird und ein leeres location.address element angegeben wird

**Comment by oliver** [comment]
Sollte jetzt durch #112 gefixt sein.
