### ISSUE TITLE
RFC: Entfernen der Karte von der Flüchtlingsseite

### ISSUE THREAD

**Issue by SimJoSt** [FreifunkBremen/bremen.freifunk.net#13]
Beim Arbeitstreffen am 15.12., haben wir uns über die Sinnhaftigkeit und Benutzung der Karte ausgetauscht.
Der Konsenz war, dass die Karte entfernt werden sollte, aus folgenden Gründen:
- Interessenten, an der Flüchtlingsarbeit Freifunks bringt sie keinen Mehrwert:
  - man möchte sehen was Freifunk schon getan hat -> nicht möglich
  - man möchte sehen, ob bei sich in der Nähe eine Unterkunft ist, um zu helfen -> nicht möglich
- die Karte ist nicht aktuell; niemand aktualisiert sie
- aufzuzeigen, was Freifunk schon alles zur Versorgung von Flüchtlingen getan hat, tut sie nicht
- sie stiftet leicht Verwirrung und wird leicht missverstanden, wenn man den Beschreibungstext nicht liest

Ein Vorschlag war, die Karte zu entfernen, jedoch den Fortschrittsbalken jedoch zu behalten und in der Seite nach oben zu verschieben.  
Er könnte eine 3. Farbe bekommen (pink?), um aufzuzeigen, welche der versorgten Unterkünfte, von Freifunk versorgt wurden.

Ideal wäre es, wenn dieser direkt aus dem Google Spreadsheet gefüttert wird, so bleibt er stets aktuell.

Um aufzuzeigen, dass daran gearbeitet wird, Flüchtlinge mit Internet zu versorgen und, dass die gespendeten Mittel verwendet werden, bieten sich am ehestens Blogposts an, welche auf der Flüchtlingsseite verlinkt werden könnten.

**Comment by mortzu** [comment]
Weg. Wir haben auch genug Karten...

**Comment by oliver** [comment]
Stimme zu, die Karte zu löschen.

**Comment by mortzu** [comment]
+1

**Comment by komaflash** [comment]
+1

> Er könnte eine 3. Farbe bekommen (pink?), um aufzuzeigen, welche der versorgten Unterkünfte, von Freifunk versorgt wurden.
Ich würde die dritte Farbe für Unterkünfte nehmen die nicht durch FF versorgt wurden.

**Comment by SimJoSt** [comment]
Karte ist bereits entfernt.
