### ISSUE TITLE
Weiße Schrift auf weißen Background

### ISSUE THREAD

**Issue by fritzlaszlo** [FreifunkBremen/bremen.freifunk.net#148]
Hi,

habe vorhin beim Firmware Download bemerkt, dass aktuell die Modellnamen in der Anzeige weiß auf weiß sind und damit nicht lesbar:

<img width="1376" alt="Screenshot 2021-01-28 at 21 34 41 copy" src="https://user-images.githubusercontent.com/3307040/106203076-27d54900-61bb-11eb-8c29-4d34445f87e9.png">

**Comment by SimJoSt** [comment]
@oliver @genofire @lokn was für Euch?

**Comment by oliver** [comment]
Guter Hinweis, danke!

Fürs Protokoll:
* es geht um die Seite https://bremen.freifunk.net/firmware.html
* der Dark Mode lässt sich im Firefox testen, wie unter https://stackoverflow.com/questions/56401662/firefox-how-to-test-prefers-color-scheme beschrieben

**Comment by genofire** [comment]
@oliver Lust denn MR zu testen?

**Comment by oliver** [comment]
Sollte jetzt gefixt sein.
