### ISSUE TITLE
Bilder in der Anleitungen skalieren

### ISSUE THREAD

**Issue by Timi7007** [FreifunkBremen/bremen.freifunk.net#30]
Die Startseite skaliert auf iPads mit Safari im Querformat nicht richtig. Unterseiten funktionieren wie erwartet. Bei "Anleitungen" tritt der Fehler auch auf.
![img_0438](https://cloud.githubusercontent.com/assets/5683832/25301499/259841a4-2729-11e7-8860-34055fafc073.PNG)
![img_0440](https://cloud.githubusercontent.com/assets/5683832/25301500/2599bcb4-2729-11e7-9ddc-8a7c0a3eb956.PNG)
Ich habe den Fehler an verschiedenen iPads verschiedener Generationen getestet. In verschiedenen Website-Test-Tools konnte ich die Situation nicht nachstellen.

Ich gehe davon aus, dass der Fehler durch die Bilder entsteht. Auf der Startseite z.B. "Partner".

**Comment by Timi7007** [comment]
Auf der Startseite ist der Fehler behoben.

Der Fehler tritt bei "Anleitungen" weiterhin auf.

**Comment by jplitza** [comment]
Die Anleitungen-Seite muss besonders design-technisch eh überarbeitet werden. Die Bilder werden alle einfach inline eingebunden und überhaupt nicht skaliert o.Ä.
