### ISSUE TITLE
Scroll-Targets bei Unterstützen nicht richtig

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/bremen.freifunk.net#45]

**Comment by mortzu** [comment]
Was ist hiermit gemeint?

**Comment by jplitza** [comment]
Beim Besuch von
https://bremen.freifunk.net/unterstuetzen.html#router-verkaufen
verschwindet die Überschrift hinter dem Header.

**Comment by genofire** [comment]
Ups, es sollte ein branch / PR werden.
Gibt es dieses Problem noch?
