### ISSUE TITLE
Probleme mit eingebetteten Bildern in Tweets

### ISSUE THREAD

**Issue by oliver** [FreifunkBremen/bremen.freifunk.net#53]
Wenn ein Tweet in der Seitenleiste auf https://bremen.freifunk.net ein Bild enthält, wird im Moment ein Thumbnail vom Twitter-Server eingebunden auf der FFHB-Seite angezeigt. Dabei gibt es zwei Probleme:

* (1) das Thumbnail wird per HTTP statt HTTPS eingebunden; dadurch kommt es zu Mixed-Content-Warnungen im Browser
* (2) beim Abrufen des Thumbnails vom Twitter-Server (pbs.twimg.com) werden Informationen an Twitter gegeben (Zeit, IP, Browsertyp, Browsersprache), was ich aus Datenschutzgründen unschön finde.

Mir fallen da folgende Lösungsmöglichkeiten ein, in ungeordneter Reihenfolge:
* a) die Thumbnails werden gar nicht mehr eingebunden (z.B. indem in api/tweets.php das $tweet_parsed['media'][]-Array nicht mehr gefüllt wird). Wenn man den Tweet dann bei Twitter anschaut, ist das Bild dort zu sehen. Löst (1) und (2), aber man hat dann halt keine Tweet-Thumbnails mehr auf der Seite.
* b) man bindet die Thumbnails per HTTPS ein. Löst nur (1). Problem (2) wird dann in Kauf genommen.
  * Implementierungs-Vorschlag a): in api/tweets.php wird auf $entity->media_url_https statt $entity->media_url zugegriffen (https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object#media)
  * Implementierungs-Vorschlag b): man setzt den HTTP-Header "Content-Security-Policy" auf "upgrade-insecure-requests" (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests)
* c) die Thumbnails werden auf dem FFHB-Webserver gecacht und von dort bereitgestellt. Löst (1) und (2); ist aber aufwändig (tweets.php muss die Bilder runterladen, soll sie aber nicht unnötig oft runterladen; veraltete Bilder müssen aus dem Cache gelöscht werden; haben wir überhaupt die Erlaubnis, Thumbnails lokal zu cachen?)
* d) die Thumbnails werden über eine Proxy-Seite des FFHB-Webservers abgerufen, welche die Bilder live vom Twitter-Webserver runterlädt. Löst (1) und (2); ist evtl. weniger aufwändig als Lösung c) (es muss kein persistenter Cache gepflegt werden), hat aber Nachteile gegenüber Lösung c) (mehr Bandbreitenbedarf; es darf kein "offener Proxy" entstehen, sondern es dürfen nur unsere eigenen Twitter-Bilder erreichbar sein; Twitter bekommt immer noch Infos über Zeiten und Zugriffszahlen).

Meiner Meinung nach sollte Lösung a) umgesetzt werden. Lösung c) wäre die qualitativ hochwertigste, aber ist halt aufwändig.

**Comment by jplitza** [comment]
Ich bin für Option d). Mit Caching kann man die Informationen, die Twitter bekommt, nochmal minimieren.

**Comment by mortzu** [comment]
@oliver @jplitza kann das einer von euch bauen?

**Comment by jplitza** [comment]
Nachdem ich das Problem von d) verstanden habe (rauszufinden, welche Bilder von uns sind und deswegen durch den Proxy dürfen), ist wohl c) doch die einfachere Variante. Zumal wir ja wissen, welche Bilder wir noch brauchen (die, die an den aktuellen Tweets dranhängen), und welche nicht.

Vielleicht komme ich da ja beim nächsten Treffen zu oder so.

**Comment by oliver** [comment]
@jplitza: prima, kannst das Ding gern implementieren! Ich hab nicht vor, da demnächst selbst was dran zu machen.

**Comment by jortgies** [comment]
ich würde gerne #107 mergen, dann ist wenigstens erstmal die mixed content warning weg

**Comment by jortgies** [comment]
Lösung c) wurde in #107 implementiert
