### ISSUE TITLE
Twitter Cards für Website (besonders Blog)

### ISSUE THREAD

**Issue by mortzu** [FreifunkBremen/bremen.freifunk.net#66]
Twitter Cards emöglichen es Tweets mit mehr Inhalten von der Website zu der gelinked wurde zu versehen. Dafür müssen auf der Website metatags gesetzt werden.
So können Beitragsvorschauen, auch mit Fotos, an Tweets gehängt werden.

- https://dev.twitter.com/cards/overview
- https://dev.twitter.com/cards/types/summary-large-image
- https://dev.twitter.com/cards/types/summary

A good place to start: http://davidensinger.com/2013/04/supporting-twitter-cards-with-jekyll/

**Comment by jortgies** [comment]
![image](https://user-images.githubusercontent.com/5610296/67675247-f3069080-f97e-11e9-99e1-10c946e560d1.png)
