### ISSUE TITLE
Termine über Webeite in Google Knowledge Graph schicken

### ISSUE THREAD

**Issue by mortzu** [FreifunkBremen/bremen.freifunk.net#67]
Ich würde sehr gerne unsere Website um ein paar Tags erweitern, damit der Google Knowledge Graph unsere Termine kennt und in der Google Karte präsent anzeigt.
An-/Einleitung: https://www.youtube.com/watch?v=XXw8g-FbemI

**Comment by genofire** [comment]
Bin wirklich zweigespalten.

## Termine
Finde es bescheiden, ein json struktur in der `<head>` zu werfen, wenn es dafür ein Datei-Format existiert.
(Auf den ich gerne ebenfalls im Header verweisen würde: https://github.com/FreifunkBremen/bremen.freifunk.net/pull/62/files#diff-99dfde12de81076a7c14ebd6972beae3R15 )

Da sollte Google nicht noch ein Datei-Format entwickeln.

## Karte
Freifunk ist kein einzelner Ort. Dies Nodes ist nicht wirklich sinnig. Meinst du den Hackerspace?

**Comment by jortgies** [comment]
> Da sollte Google nicht noch ein Datei-Format entwickeln.
wenn ich das richtig sehe, ist das nicht direkt ein von Google entwickeltes Format sondern gehört zu [schema.org](https://schema.org/docs/gs.html)
IMO spricht da nichts gegen, es müsste sich nur jemand finden der das einbaut

**Comment by jortgies** [comment]
ich hab mal ein bisschen js dafür geschrieben, bitte einmal schauen ob ihr das so ok findet @mortzu @genofire 
das json-ld ist nach dem [schema.org Standard](https://schema.org/Event)
überprüft hab ich das hiermit https://search.google.com/structured-data/testing-tool

**Comment by mortzu** [comment]
Da gemerged kann das zu?

**Comment by oliver** [comment]
Hab grad mal https://ffhb.de/ mit https://search.google.com/structured-data/testing-tool getestet, aber da wurden wohl keine strukturierten Elemente erkannt. Sollte man nochmal untersuchen, bevor das Issue geschlossen wird.

**Comment by jortgies** [comment]
@oliver scheinbar hat google zwei verschiedene tools zum testen, hier z.b. funktioniert es https://search.google.com/test/rich-results?id=UjEFrGOtwin4Pud4d6jEZg

anscheinend kann das andere tool kein js parsen und zeigt die ereignisse deswegen nicht an

**Comment by mortzu** [comment]
dann kanns zu? :)

**Comment by oliver** [comment]
ja, dann kann das Issue zu. @jortgies: danke fürs Nachhaken!
