### ISSUE TITLE
Externe Links im Menu

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/bremen.freifunk.net#74]
Es wäre sinnvoll externe Links zu Kennzeichnen (und in ein neuen Tab öffnen lassen)

Externe Links wäre:
- Startseite -> Karte
- Engagieren -> Wiki

**Comment by lokn** [comment]
Meinst du alle Links, auch in Blogbeiträgen?

Eine Möglichkeit wäre externe Links mit CSS automatisch zu kennzeichnen **a[href ^= "http"]:after {}**: http://jsfiddle.net/ZkbKp/
Automatisch in neuem Tab öffnen zu lassen scheint nur per JavaScript zu funktionieren.

**Comment by jortgies** [comment]
ich hab den vorschlag von @lokn mal eingebaut PR #110 

sieht so aus:
![image](https://user-images.githubusercontent.com/5610296/67121899-e058c280-f1ec-11e9-8a3a-84a57153e8f4.png)

![image](https://user-images.githubusercontent.com/5610296/67121875-d46d0080-f1ec-11e9-91e8-aada07075c9c.png)

**Comment by oliver** [comment]
Ich hab den PR von @jortgies mal lokal ausprobiert (danke fürs Umsetzen!) und bin jetzt nicht mehr sicher, wofür diese ganze Änderung gedacht ist bzw. ob die insgesamt sinnvoll ist.

Alle Links zu unserem Wiki (oder z.B. zu downloads.ffhb.de oder lists.ffhb.de) sind jetzt als "extern" markiert; aber ich hab diese Seiten nie als "extern" angesehen, sondern als Teil unseres gesamten Auftritts (die nur aus technischen Gründen anders aussehen und auf anderen URLs liegen).

Es ist halt auch tatsächlich nicht so, dass alle externen Links im neuen Fenster geöffnet werden; d.h. das Icon ist hier kein sinnvoller Hinweis auf "wird im neuen Fenster geöffnet", weil man sich halt nicht drauf verlassen kann.

Davon abgesehen ist der eingebundene Twitter-Feed jetzt voll von den "Extern"-Icons, weil da halt sehr viele Links drin sind.
Ebenso steht jetzt in der Liste der Sponsoren (unten auf der Hauptseite) bei jedem Logo ein solches Icon.

Ich fänds gut, wenn hier nochmal zusammentragen werden könnte, welchen Zweck das Icon haben soll, und in welchen Fällen das Icon auftauchen und in welchen nicht.

**Comment by jortgies** [comment]
wurde am 3. Juli mit c37f6fd5c1870e6d95454cfd2eaaa56bc52e664d gemerged
