### ISSUE TITLE
Knotenanzahl wird wegen CORS-Problem nicht angezeigt

### ISSUE THREAD

**Issue by oliver** [FreifunkBremen/bremen.freifunk.net#80]
Auf der ffhb.de-Hauptseite soll eigentlich auf dem großen Kartenbild unter dem Link "Zur Knotenkarte" noch die Anzahl der aktuellen Knoten und Nutzer angezeigt werden. Diese Daten werden auch bei Grafana abgefragt, aber die Abfrage geht (zumindest in meinem Browser) wegen Problemen mit [CORS (Cross-Origin Resource Sharing)](https://de.wikipedia.org/wiki/Cross-Origin_Resource_Sharing) schief. In der Firefox-Konsole steht dazu die Fehlermeldung:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://grafana.bremen.freifunk.net/api/datasources/proxy/1/query?db=ffhb-nodes&q=SELECT%20last(%22clients.total%22)%20AS%20%22clients%22%2C%20last(%22nodes%22)%20AS%20%22nodes%22%20FROM%20%22global%22&u=public&p=public. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Soweit ich das verstehe, ist CORS nötig, um die [Same-origin policy](https://en.wikipedia.org/wiki/Same-origin_policy) einzuhalten und damit zu vermeiden, dass dem Nutzer bösartige HTTP-Requests untergeschoben werden zu einer Webseite, auf der sein Browser eingeloggt ist. Bei unserer Grafana-Seite sollte das reine _Abrufen_ von Daten ungefährlich sein; aber man kann sich ja auch auf dem Server (zumindest im Grafana-Frontend) einloggen, und deshalb sollten wir diese Same-origin policy für _verändernde_ Requests nicht komplett aushebeln.

Als Lösungen fallen mir im Moment ein:
- auf dem Grafana-Server einen passenden "Access-Control-Allow-Origin"-Header einbauen, aber eben nur für lesende Queries und/oder nur für unsere bremen.freifunk.net und ffhb.de
- auf ffhb.de einen Proxy für diese Grafana-Daten aufsetzen, damit der Browser keinen Query zu grafana.bremen.freifunk.net schicken muss
- die Daten über irgendeinen anderen Query-Mechanismus aus Grafana holen, so dass CORS gar nicht zum Zuge kommt
- die Daten periodisch auf dem Server aus Grafana holen und als Datei auf ffhb.de ablegen, damit der Browser keinen Query zu grafana.bremen.freifunk.net schicken muss
- die Anzeige von Knoten-/Nutzeranzahl ganz rausnehmen

**Comment by genofire** [comment]
Ich hab nun erstmal den Apache angepasst, das er von `*ffhb.de` und `*bremen.freifunk.net` den passenden Access-Control-Allow-Origin"-Header mitgibt.

folgenden Config dazugepackt:
```
  # Sets CORS headers for request from example1.com and example2.com pages
  # for both SSL and non-SSL
  SetEnvIf Origin "^https?://[^/]*(ffhb\.de|bremen\.freifunk\.net)$" ORIGIN=$0
  Header set Access-Control-Allow-Origin %{ORIGIN}e env=ORIGIN
  Header set Access-Control-Allow-Credentials "true" env=ORIGIN
  # Always set Vary: Origin when it's possible you may send CORS headers
  Header merge Vary Origin
```

Wie wir es dauerhaft machen wollen keine Ahnung.
1. Done, erstmal einfachste Variante
2. Nope, solange die Struktur der Daten nicht geändert wird - da 1. ist ja okay
3. ...
4. Bin kein Fan von extra Datei, falls ein Cronjob oder so nicht mehr läuft, zeigt er ein status von vor X Jahren an.
5. Lieber deadcode, als komplett rausnehmen (find es cool + es ist gut programmiert, sodass es garnicht auffällt wenn es tot ist)

**Comment by mortzu** [comment]
dann bin ich fuer zu. Es laeuft und ich find die Loesung ok

**Comment by oliver** [comment]
Ich find die CORS-Änderung auch gut; die müsste wohl noch in https://github.com/FreifunkBremen/ansible/blob/master/roles/grafana/templates/apache2.conf übernommen werden.

**Comment by genofire** [comment]
Ups, mein Job

**Comment by genofire** [comment]
Done: https://github.com/FreifunkBremen/ansible/commit/8eb517e66233943dfa035cc52be812453ab61877
