### ISSUE TITLE
Broken (legacy) Posts

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/bremen.freifunk.net#87]
- broken markdown: https://bremen.freifunk.net/blog/2014/09/21/auswertung-kanalanalyse.html
- Video at YouTube dropped: https://bremen.freifunk.net/blog/2014/12/22/buten-un-binnen.html

**Comment by jortgies** [comment]
> broken markdown:

konnten @lokn und ich nicht nachvollziehen, die seite sieht ok aus

> Video at YouTube dropped:

können wir leider nicht viel machen. vielleicht den letzten absatz entfernen oder darauf hinweisen dass das video nicht mehr existiert?

**Comment by oliver** [comment]
Ups, das kaputte Markdown im Kanalanalyse-Post hatte ich neulich mal gefixt (in c3378b8f902c902fc5464aa282bb87377537227f), und hatte nicht gemerkt, dass es dafür ein eigenes Issue gibt.
