### ISSUE TITLE
Link zum Github-Repo

### ISSUE THREAD

**Issue by oliver** [FreifunkBremen/bremen.freifunk.net#90]
Es sollte irgendwo auf der Webseite einen Link zu unserem Github-Repo (https://github.com/FreifunkBremen/) geben. Im Moment ist es für technisch Interessierte schwierig, von https://bremen.freifunk.net/ z.B. zu unserer Gluon-Config zu kommen.

Ideen:
- Link unter https://ffhb.de/technik.html hinzufügen
- eigenen Menüpunkt (z.B. "Git" oder "Quelltext") als Unterpunkt von "Engagierte" hinzufügen
- Link zu https://github.com/FreifunkBremen/gluon-site-ffhb auf https://ffhb.de/firmware.html (z.B. mit dem Text "Der Quelltext für unsere Firmware ist frei verfügbar unter https://github.com/FreifunkBremen/gluon-site-ffhb")
- Link zu https://github.com/FreifunkBremen/ auf https://ffhb.de/kontakt.html (als weiterer Punkt hinter Mastodon etc.)
- Link zu https://github.com/FreifunkBremen zu die Social-Media-Icons in der Menüleiste hinzufügen

**Comment by jplitza** [comment]
Bin für alle Varianten bis auf kontakt.html

**Comment by genofire** [comment]
Here is the logo for git: https://git-scm.com/downloads/logos
(if we move away from github)

**Comment by oliver** [comment]
Hurra @lokn und @genofire, vielen Dank fürs Fixen :heart:

Von mir aus würd ich dieses Issue jetzt schließen; oder wollt ihr noch Links an anderen Stellen einbauen?

**Comment by lokn** [comment]
Wir könnten das Logo noch in die Icon-Leiste einbauen.
Da gibt es aber gelegentlich noch Anzeigefehler. Die sollten erst behoben werden.

**Comment by jplitza** [comment]
@lokn: Magst du für die Anzeigefehler ein Issue machen? Dann kann ich mal versuchen mir das anzugucken.

**Comment by lokn** [comment]
#97 angelegt

**Comment by lokn** [comment]
In Social Icon Liste eingebaut.

**Comment by oliver** [comment]
@lokn: kannst du den Github-Link in der Icon-Leiste noch mal ändern, so dass der zu https://github.com/FreifunkBremen führt (statt zu https://github.com/FreifunkBremen/gluon-site-ffhb)? Dann sieht man gleich die ganzen Repos, die wir so haben, statt nur das Firmware-Repo.

**Comment by lokn** [comment]
Done
