### ISSUE TITLE
Überlappung der Icon-Leiste mit Freifunklogo

### ISSUE THREAD

**Issue by lokn** [FreifunkBremen/bremen.freifunk.net#97]
Bei Fenster-Breiten zwischen etwa 1114px und 1107px überlappen sich die Icons und das Hintergrundlogo oben rechts.
Ab etwa 1107px wird das Hintergrundlogo ausgeblendet.
Dies sollte bereits ab 1114px passieren.
<img width="226" alt="Bildschirmfoto 2019-08-09 um 12 02 00" src="https://user-images.githubusercontent.com/20230168/62771454-8ecde200-ba9d-11e9-8651-f36865b162f9.png">

Zwischen etwa 722px und 720px Breite überlappen sich stückweise die Icons mit den Menü-Punkten.
Ab etwa 719px wechselt das Layout zur mobilen Version. Dann werden die Icons wieder richtig im Menü angezeigt.
<img width="375" alt="Bildschirmfoto 2019-08-09 um 12 03 03" src="https://user-images.githubusercontent.com/20230168/62771541-bf158080-ba9d-11e9-9c2e-1c5145f6365f.png">

**Comment by jplitza** [comment]
Das Problem ist, dass die Grenzen nicht nur für den Header gelten, sondern auch für den Content: Der normale Content wird bis zu 720px breit, der auf der Startseite bis zu 1108px. Letzteres ist offensichtlich ein relativ willkürlicher Wert den man auch anders wählen könnte (dann sieht halt die Startseite anders aus), ersteres sollte halt genau eine gewisse Geräteklasse noch mit umfassen (keine Ahnung, ob das heutzutage auf High-DPI-Geräten noch ne Rolle spielt).
